
let db={types:[{id:1,n:"Gemeente"},{id:2,n:"Jeugdbescherming"},{id:3,n:"Veilig Thuis"},{id:4,n:"GGD"},{id:5,n:"Politie"}],orgs:[{id:1,t:1,n:"Almelo"},{id:2,t:1,n:"Hengelo"},{id:3,t:1,n:"Tubbergen"},{id:4,t:2,n:"JBOV"},{id:5,t:2,n:"Leger des Heils"},{id:6,t:3,n:"Veilig Thuis Twente"}],contacts:[{id:1,o:1,n:"Jan Jansen",f:"Jeugdconsulent",m:"06-12345678",tel:"0546-123456",e:"jan.jansen@almelo.nl",op:"Werkt ma-do",mo:[1]},{id:2,o:1,n:"Harry Nak",f:"Contractmanager",m:"0612457896",tel:"",e:"",op:"di-do",mo:[1]},{id:3,o:4,n:"Nico de Groot",f:"Jeugdbeschermer",m:"06-12365478",tel:"",e:"",op:"Alleen mailen",mo:[1]},{id:4,o:6,n:"Petra de Vries",f:"Adviseur",m:"06-87654321",tel:"",e:"petra@example.nl",op:"",mo:[2]}],mothers:[{id:1,n:"Maria Jansen",op:"Voorkeur telefonisch contact.",a:1,k:[1,2]},{id:2,n:"Anne de Vries",op:"Eerst via contactpersoon afstemmen.",a:1,k:[3]},{id:3,n:"Karin Bakker",op:"",a:1,k:[5,6,7]},{id:4,n:"Moeder Oud",op:"Niet meer actief.",a:0,k:[4]}],kids:[{id:1,n:"Lisa Jansen",mo:1},{id:2,n:"Milan Jansen",mo:1},{id:3,n:"Saar de Vries",mo:2},{id:4,n:"Oud Kind",mo:4},{id:5,n:"Emma Bakker",mo:3},{id:6,n:"Julia Bakker",mo:3},{id:7,n:"Noah Bakker",mo:3}]};
let st={p:"home",id:null,q:"",inline:"",d:null,modal:null,ct:"all",co:"all"};
const app=document.getElementById("app"), by=(a,id)=>a.find(x=>x.id==id), type=id=>by(db.types,id), org=id=>by(db.orgs,id), con=id=>by(db.contacts,id), mom=id=>by(db.mothers,id), nid=a=>Math.max(0,...a.map(x=>x.id))+1;
function consOrg(id){return db.contacts.filter(c=>c.o==id)} function consMom(id){return db.contacts.filter(c=>c.mo.includes(+id))} function kidsMom(id){return db.kids.filter(k=>k.mo==id)} function meta(c){let o=org(c.o),t=type(o.t);return `${t.n} | ${o.n} | ${c.f||""}`}
function go(p,id=null){st={...st,p,id,q:"",inline:"",d:null,modal:null}; if(p==="contacts"){st.ct="all";st.co="all"} render()} function sq(v){st.q=v;render()} function si(v){st.inline=v;render()} function od(k,ctx={}){st.d={k,ctx};st.modal=null;render()} function cd(){st.d=null;st.modal=null;render()} function om(k,ctx={}){st.modal={k,ctx};render()} function cm(){st.modal=null;render()} 
function sct(v){st.ct=v;st.co="all";renderContactsList()} function sco(v){st.co=v;renderContactsList()}

function shell(c){return `<div class="app"><aside class="side"><div class="brand"><img src="./logo.png" onerror="this.style.display='none'"><div><div class="bt">Contacten</div><div class="bo">Het Twentse Geluk</div></div></div><div class="search"><input value="${esc(st.q)}" oninput="sq(this.value)" placeholder="Zoeken..."></div><nav class="nav"><button class="${st.p=="home"?"a":""}" onclick="go('home')">Home</button><button class="${["orgs","type","org"].includes(st.p)?"a":""}" onclick="go('orgs')">Organisaties</button><button class="${["contacts","contact"].includes(st.p)?"a":""}" onclick="go('contacts')">Contactpersonen</button><button class="${["mothers","mother"].includes(st.p)?"a":""}" onclick="go('mothers')">Moeders</button><button class="${["kids","kid"].includes(st.p)?"a":""}" onclick="go('kids')">Kinderen</button></nav></aside><main class="main">${c}</main></div>${st.d?drawer():""}${st.modal?modal():""}`}
function home(){return `<div class="hero"><h2>Contacten</h2></div><div class="home"><button onclick="od('mother')">Nieuwe moeder</button><button onclick="od('kid')">Nieuw kind</button><button onclick="od('contact')">Nieuw contactpersoon</button><button onclick="om('org')">Nieuwe organisatie</button></div>`}
function orgs(){let ts=db.types.filter(t=>db.orgs.some(o=>o.t==t.id&&consOrg(o.id).length));return `<div class="toolbar"><h2>Organisaties</h2><div class="actions"><button class="btn primary" onclick="om('org')">Nieuwe organisatie</button><button class="btn primary" onclick="om('type')">Nieuw type organisatie</button></div></div><div class="type-grid">${ts.map(t=>`<button class="type-card" onclick="go('type',${t.id})"><strong>${t.n}</strong><span>${db.orgs.filter(o=>o.t==t.id&&consOrg(o.id).length).length} organisaties</span></button>`).join("")}</div>`}
function typePage(id){let t=type(id), rows=db.orgs.filter(o=>o.t==id&&consOrg(o.id).length);return `<button class="back" onclick="go('orgs')">← Terug naar organisaties</button><div class="toolbar"><h2>${t.n}</h2><button class="btn primary" onclick="od('contact',{type:${id}})">Nieuwe contactpersoon</button></div><div class="cards">${rows.map(o=>`<button class="rowbtn" onclick="go('org',${o.id})"><div><strong>${o.n}</strong></div><div><span>${consOrg(o.id).length} contactpersonen</span></div><div class="chev">›</div></button>`).join("")}</div>`}
function orgPage(id){let o=org(id),t=type(o.t),cs=consOrg(id);return `<button class="back" onclick="go('type',${o.t})">← Terug naar ${t.n}</button><div class="hero"><h2>${o.n}</h2><p>Type organisatie: <strong>${t.n}</strong></p></div><div class="toolbar"><h2>Contactpersonen</h2><div class="actions"><button class="btn secondary">Bewerken</button><button class="btn danger">Verwijderen</button><button class="btn primary" onclick="od('contact',{org:${id}})">Nieuwe contactpersoon</button></div></div><div class="cards">${cs.map(contactRow).join("")}</div>`}
function contacts(){let orgOpts=orgOptions();return `<div class="toolbar"><h2>Contactpersonen</h2><button class="btn primary" onclick="od('contact')">Nieuwe contactpersoon</button></div><div class="filters"><div class="filter"><label>Zoeken op naam</label><input id="contactNameSearch" value="" oninput="renderContactsList()" placeholder="Naam contactpersoon"></div><div class="filter"><label>Type organisatie</label><select id="contactTypeFilter" onchange="updateOrgFilterOptions();renderContactsList()"><option value="all">Alle types</option>${db.types.map(t=>`<option value="${t.id}">${t.n}</option>`).join("")}</select></div><div class="filter"><label>Organisatie</label><select id="contactOrgFilter" onchange="renderContactsList()"><option value="all">Alle organisaties</option>${orgOpts.map(o=>`<option value="${o.id}">${o.n}</option>`).join("")}</select></div></div><div class="cards" id="contactResults">${contactResults().map(contactRow).join("")}</div>`}
function orgOptions(){let sel=document.getElementById("contactTypeFilter")?.value||"all";return db.orgs.filter(o=>(sel==="all"||o.t==sel)&&consOrg(o.id).length)}
function updateOrgFilterOptions(){let select=document.getElementById("contactOrgFilter");select.innerHTML=`<option value="all">Alle organisaties</option>`+orgOptions().map(o=>`<option value="${o.id}">${o.n}</option>`).join("")}
function contactResults(){let q=(document.getElementById("contactNameSearch")?.value||"").toLowerCase(), tid=document.getElementById("contactTypeFilter")?.value||"all", oid=document.getElementById("contactOrgFilter")?.value||"all";return db.contacts.filter(c=>{let o=org(c.o);return (tid==="all"||o.t==tid)&&(oid==="all"||c.o==oid)&&(!q||c.n.toLowerCase().includes(q))})}
function renderContactsList(){let el=document.getElementById("contactResults");if(el)el.innerHTML=contactResults().map(contactRow).join("")}
function contactRow(c){return `<button class="rowbtn" onclick="go('contact',${c.id})"><div><strong>${c.n}</strong></div><div><span>${meta(c)}</span></div><div class="chev">›</div></button>`}
function contactPage(id){let c=con(id),o=org(c.o),t=type(o.t),ms=db.mothers.filter(m=>c.mo.includes(m.id));return `<button class="back" onclick="go('contacts')">← Terug</button><div class="hero"><h2>${c.n}</h2><p>${c.f||""}</p></div><div class="grid"><div class="panel">${info("Type organisatie",t.n)}${info("Organisatie",o.n)}${info("Mobiel",c.m||"—")}${info("Telefoon",c.tel||"—")}${info("E-mail",c.e||"—")}${info("Opmerkingen",c.op||"—")}<div class="formactions"><button class="btn secondary">Bewerken</button><button class="btn danger">Verwijderen</button></div></div><div class="panel"><h3>Moeders</h3><div class="chips">${ms.map(m=>`<button onclick="go('mother',${m.id})">${m.n}</button>`).join("")}</div></div></div>`}
function mothers(){let rows=db.mothers.filter(m=>m.a&&(!st.inline||m.n.toLowerCase().includes(st.inline.toLowerCase())));return `<div class="toolbar"><h2>Moeders</h2><button class="btn primary" onclick="od('mother')">Nieuwe moeder</button></div><div class="filter" style="max-width:560px;margin-bottom:18px"><label>Zoeken</label><input value="${esc(st.inline)}" oninput="si(this.value)" placeholder="Zoek moeder..."></div><div class="cards">${rows.map(m=>`<button class="rowbtn" onclick="go('mother',${m.id})"><div><strong>${m.n}</strong></div><div><span>Actief</span></div><div class="chev">›</div></button>`).join("")}</div>`}
function motherPage(id){let m=mom(id),ks=kidsMom(id),cs=consMom(id);return `<button class="back" onclick="go('mothers')">← Terug naar moeders</button><div class="profile split"><div><h2>${m.n}</h2><p>${m.op||""}</p></div><div><div class="title">Kinderen</div><div class="list">${ks.map(k=>`<button class="pill" onclick="go('mother',${m.id})">${k.n}</button>`).join("")}<button class="btn primary" onclick="od('kid',{mother:${id}})">Nieuw kind</button></div></div></div><div class="panel"><h3>Contactpersonen</h3><div class="cards">${cs.map(contactRow).join("")}</div><div class="section-actions"><button class="btn primary" onclick="od('link',{mother:${id}})">Contactpersoon toevoegen</button></div></div><div class="formactions"><button class="btn secondary">Bewerken</button><button class="btn secondary">Inactief maken</button></div>`}
function kids(){let groups=db.mothers.filter(m=>m.a).sort((a,b)=>a.n.localeCompare(b.n,'nl')).map(m=>({m,k:kidsMom(m).sort((a,b)=>a.n.localeCompare(b.n,'nl'))})).filter(g=>g.k.length);return `<div class="toolbar"><h2>Kinderen</h2><button class="btn primary" onclick="od('kid')">Nieuw kind</button></div><div class="kid-groups">${groups.map(g=>`<div class="kid-group"><button class="kid-mom" onclick="go('mother',${g.m.id})">${g.m.n}</button>${g.k.map(k=>`<button class="kid-child" onclick="go('mother',${g.m.id})">${first(k.n)}</button>`).join("")}</div>`).join("")}</div>`}
function first(n){return n.split(" ")[0]}
function kidPage(id){let k=by(db.kids,id),m=mom(k.mo);return motherPage(m.id)}
function drawer(){let d=st.d;if(d.k=="mother")return drawMother();if(d.k=="kid")return drawKid();if(d.k=="contact")return drawContact();if(d.k=="link")return drawLink()}
function drawMother(){return `<div class="drawerbg"><aside class="drawer"><h2>Nieuwe moeder</h2><div class="field"><label>Naam</label><input id="mn" autofocus></div><div class="field"><label>Opmerkingen</label><textarea id="mop"></textarea></div><div class="formactions"><button class="btn secondary" onclick="cd()">Annuleren</button><button class="btn primary" onclick="saveMother()">Opslaan</button></div></aside></div>`}
function drawKid(){let mid=st.d.ctx.mother||db.mothers.find(m=>m.a).id;return `<div class="drawerbg"><aside class="drawer"><h2>Nieuw kind</h2><div class="field"><label>Naam</label><input id="kn" autofocus></div><div class="field"><label>Moeder</label><select id="km">${db.mothers.filter(m=>m.a).map(m=>`<option value="${m.id}" ${m.id==mid?"selected":""}>${m.n}</option>`).join("")}</select></div><div class="formactions"><button class="btn secondary" onclick="cd()">Annuleren</button><button class="btn primary" onclick="saveKid()">Opslaan</button></div></aside></div>`}
function drawContact(){let oid=st.d.ctx.org||db.orgs[0].id,o=org(oid),tid=st.d.ctx.type||o.t;return `<div class="drawerbg"><aside class="drawer"><h2>Nieuwe contactpersoon</h2>${st.d.ctx.mother?`<input id="cmo" type="hidden" value="${st.d.ctx.mother}">`:""}${typePick(tid)}${orgAuto(oid)}<div class="field"><label>Naam</label><input id="cn"></div><div class="field"><label>Functie</label><input id="cf"></div><div class="field"><label>Mobiel</label><input id="cmob"></div><div class="field"><label>Telefoon</label><input id="ctel"></div><div class="field"><label>E-mail</label><input id="ce"></div><div class="field"><label>Opmerkingen</label><textarea id="cop"></textarea></div><div id="warn"></div><div class="formactions"><button class="btn secondary" onclick="cd()">Annuleren</button><button class="btn primary" onclick="saveContact()">Opslaan</button></div></aside></div>`}
function typePick(tid){return `<div class="field"><label>Type organisatie</label><select id="ct" onchange="updateOrgAuto()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div>`}
function orgAuto(oid){let o=org(oid);return `<div class="field"><label>Organisatie</label><div class="formrow"><input id="oterm" value="${esc(o.n)}" oninput="updateOrgAuto()" placeholder="Typ organisatie..."><button class="btn secondary" onclick="om('org')">Nieuw</button></div><input id="selorg" type="hidden" value="${oid}"><div id="omatch"></div></div>`}
function drawLink(){let mid=st.d.ctx.mother,tid=st.d.ctx.type||db.types[0].id,orgs=db.orgs.filter(o=>o.t==tid),oid=st.d.ctx.org||orgs[0].id,cs=db.contacts.filter(c=>c.o==oid&&!c.mo.includes(mid));return `<div class="drawerbg"><aside class="drawer"><h2>Contactpersoon toevoegen</h2><div class="field"><label>Type organisatie</label><select onchange="st.d.ctx.type=+this.value;st.d.ctx.org=null;render()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Organisatie</label><div class="formrow"><select onchange="st.d.ctx.org=+this.value;render()">${orgs.map(o=>`<option value="${o.id}" ${o.id==oid?"selected":""}>${o.n}</option>`).join("")}</select><button class="btn secondary" onclick="om('org')">Nieuw</button></div></div><h3>Bekende contactpersonen</h3><div class="cards">${cs.map(c=>`<button class="rowbtn" onclick="linkCon(${c.id},${mid})"><div><strong>${c.n}</strong></div><div><span>${meta(c)}</span></div><div class="chev">›</div></button>`).join("")}</div><div class="section-actions"><button class="btn primary" onclick="od('contact',{mother:${mid},org:${oid}})">Nieuwe contactpersoon</button></div><div class="formactions"><button class="btn secondary" onclick="cd()">Sluiten</button></div></aside></div>`}
function modal(){if(st.modal.k=="type")return `<div class="modalbg"><div class="modal"><h2>Nieuw type organisatie</h2><div class="field"><label>Naam</label><input id="tn" autofocus></div><div class="formactions"><button class="btn secondary" onclick="cm()">Annuleren</button><button class="btn primary" onclick="saveType()">Opslaan</button></div></div></div>`;let tid=+(document.getElementById("ct")?.value||st.d?.ctx?.type||1);return `<div class="modalbg"><div class="modal"><h2>Nieuwe organisatie</h2><div class="field"><label>Type organisatie</label><select id="nt">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Naam organisatie</label><input id="on" autofocus></div><div class="formactions"><button class="btn secondary" onclick="cm()">Annuleren</button><button class="btn primary" onclick="saveOrg()">Opslaan</button></div></div></div>`}
function saveMother(){let n=v("mn"),op=v("mop");if(!n)return alert("Vul een naam in.");let id=nid(db.mothers);db.mothers.push({id,n,op,a:1,k:[]});go("mother",id)}
function saveKid(){let n=v("kn"),mo=+v("km");if(!n)return alert("Vul een naam in.");let id=nid(db.kids);db.kids.push({id,n,mo});mom(mo).k.push(id);cd()}
function saveType(){let n=v("tn");if(!n)return alert("Vul een naam in.");if(db.types.some(t=>t.n.toLowerCase()==n.toLowerCase()))return alert("Dit type organisatie bestaat al.");db.types.push({id:nid(db.types),n});cm()}
function saveOrg(){let n=v("on"),t=+v("nt");if(!n)return alert("Vul een naam organisatie in.");if(db.orgs.some(o=>o.t==t&&o.n.toLowerCase()==n.toLowerCase()))return alert("Deze organisatie bestaat al binnen dit type organisatie.");let id=nid(db.orgs);db.orgs.push({id,t,n});cm()}
function saveContact(force=false){let o=+v("selorg"),n=v("cn"),m=v("cmob"),e=v("ce");if(!o)return alert("Kies een organisatie.");if(!n)return alert("Vul een naam in.");if(!force){let dup=db.contacts.find(c=>(c.o==o&&c.n.toLowerCase()==n.toLowerCase())||(m&&c.m==m)||(e&&c.e.toLowerCase()==e.toLowerCase()));if(dup){document.getElementById("warn").innerHTML=`<div class="warn"><strong>Mogelijke dubbele contactpersoon</strong>${dup.n}<br>${meta(dup)}<div class="formactions"><button class="btn secondary" onclick="go('contact',${dup.id})">Bestaande openen</button><button class="btn primary" onclick="saveContact(true)">Toch opslaan</button></div></div>`;return}}let id=nid(db.contacts),mo=+(document.getElementById("cmo")?.value||0);db.contacts.push({id,o,n,f:v("cf"),m,tel:v("ctel"),e,op:v("cop"),mo:mo?[mo]:[]});cd()}
function linkCon(cid,mid){let c=con(cid);if(!c.mo.includes(mid))c.mo.push(mid);cd()}
function updateOrgAuto(){let tid=+v("ct"),term=v("oterm").toLowerCase(),matches=db.orgs.filter(o=>o.t==tid&&(!term||o.n.toLowerCase().includes(term)));document.getElementById("omatch").innerHTML=`<div class="ac">${matches.map(o=>`<button onclick="selectOrg(${o.id})">${o.n}</button>`).join("")}</div>`}
function selectOrg(id){document.getElementById("selorg").value=id;document.getElementById("oterm").value=org(id).n;document.getElementById("omatch").innerHTML=""}
function searchPage(){let q=st.q.toLowerCase();return `<div class="hero"><h2>Resultaten voor “${esc(st.q)}”</h2></div>${group("Contactpersonen",db.contacts.filter(c=>[c.n,meta(c),c.m,c.e].some(x=>(x||"").toLowerCase().includes(q))).map(contactRow))}${group("Moeders",db.mothers.filter(m=>m.n.toLowerCase().includes(q)).map(m=>`<button class="pill" onclick="go('mother',${m.id})">${m.n}</button>`))}`}
function group(t,rows){return `<section class="panel"><h3>${t}</h3><div class="cards">${rows.length?rows.join(""):`<p class="muted">Geen resultaten.</p>`}</div></section>`}
function info(l,x){return `<div class="info"><label>${l}</label><strong>${x}</strong></div>`}
function v(id){return document.getElementById(id)?.value.trim()||""}
function esc(s){return String(s||"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function render(){let c="";if(st.q)c=searchPage();else if(st.p=="home")c=home();else if(st.p=="orgs")c=orgs();else if(st.p=="type")c=typePage(st.id);else if(st.p=="org")c=orgPage(st.id);else if(st.p=="contacts")c=contacts();else if(st.p=="contact")c=contactPage(st.id);else if(st.p=="mothers")c=mothers();else if(st.p=="mother")c=motherPage(st.id);else if(st.p=="kids")c=kids();else if(st.p=="kid")c=kidPage(st.id);app.innerHTML=shell(c)}
render();
