
const db={
 types:[{id:1,n:"Gemeente"},{id:2,n:"Jeugdbescherming"},{id:3,n:"Veilig Thuis"},{id:4,n:"GGD"},{id:5,n:"Politie"},{id:6,n:"Onderwijs"}],
 orgs:[{id:1,t:1,n:"Almelo"},{id:2,t:1,n:"Hengelo"},{id:3,t:1,n:"Tubbergen"},{id:4,t:2,n:"JBOV"},{id:5,t:2,n:"Leger des Heils"},{id:6,t:3,n:"Veilig Thuis Twente"}],
 contacts:[{id:1,o:1,n:"Jan Jansen",f:"Jeugdconsulent",m:"06-12345678",tel:"0546-123456",e:"jan.jansen@almelo.nl",op:"Werkt ma-do",mo:[1]},{id:2,o:1,n:"Harry Nak",f:"Contractmanager",m:"0612457896",tel:"",e:"",op:"di-do",mo:[1]},{id:3,o:4,n:"Nico de Groot",f:"Jeugdbeschermer",m:"06-12365478",tel:"",e:"",op:"Alleen mailen",mo:[1]},{id:4,o:6,n:"Petra de Vries",f:"Adviseur",m:"06-87654321",tel:"",e:"petra@example.nl",op:"",mo:[2]}],
 mothers:[{id:1,n:"Maria Jansen",op:"Voorkeur telefonisch contact.",a:1,k:[1,2]},{id:2,n:"Anne de Vries",op:"Eerst via contactpersoon afstemmen.",a:1,k:[3]},{id:3,n:"Karin Bakker",op:"",a:1,k:[5,6,7]},{id:4,n:"Moeder Oud",op:"Niet meer actief.",a:0,k:[4]}],
 kids:[{id:1,n:"Lisa Jansen",mo:1},{id:2,n:"Milan Jansen",mo:1},{id:3,n:"Saar de Vries",mo:2},{id:4,n:"Oud Kind",mo:4},{id:5,n:"Emma Bakker",mo:3},{id:6,n:"Julia Bakker",mo:3},{id:7,n:"Noah Bakker",mo:3}]
};
let st={page:"mothers",id:null,global:"",motherQ:"",kidQ:"",drawer:null,modal:null};
const app=document.getElementById("app");
const by=(a,id)=>a.find(x=>x.id==id), type=id=>by(db.types,id), org=id=>by(db.orgs,id), contact=id=>by(db.contacts,id), mother=id=>by(db.mothers,id), kid=id=>by(db.kids,id), nid=a=>Math.max(0,...a.map(x=>x.id))+1;
function consOrg(id){return db.contacts.filter(c=>c.o==id)}
function consMom(id){return db.contacts.filter(c=>c.mo.includes(+id))}
function kidsMom(id){return db.kids.filter(k=>k.mo==id)}
function meta(c){let o=org(c.o),t=type(o.t);return `${t.n} | ${o.n} | ${c.f||""}`}
function nav(page,id=null){st={...st,page,id,global:"",motherQ:"",kidQ:"",drawer:null,modal:null};render()}
function setGlobal(v){st.global=v;renderGlobalOnly()}
function openDrawer(kind,ctx={}){st.drawer={kind,ctx};st.modal=null;render()}
function closeDrawer(){st.drawer=null;st.modal=null;render()}
function openModal(kind,ctx={}){st.modal={kind,ctx};render()}
function closeModal(){st.modal=null;render()}
function shell(content){return `<div class="app"><aside class="sidebar"><div class="brand"><img src="./logo.png" onerror="this.style.display='none'"><div><div class="brand-title">Contacten</div><div class="brand-org">Het Twentse Geluk</div></div></div><div class="search-wrap"><div class="global-search"><input id="globalInput" value="${esc(st.global)}" oninput="setGlobal(this.value)" placeholder="Zoek overal..."></div></div><nav class="nav"><button class="${st.page==="mothers"?"active":""}" onclick="nav('mothers')">Moeders</button><button class="${st.page==="kids"?"active":""}" onclick="nav('kids')">Kinderen</button><button class="${["contacts","contact"].includes(st.page)?"active":""}" onclick="nav('contacts')">Contactpersonen</button><button class="${["orgs","type","org"].includes(st.page)?"active":""}" onclick="nav('orgs')">Organisaties</button></nav></aside><main class="main">${content}</main></div><div id="globalResultsHost">${globalResults()}</div>${st.drawer?drawer():""}${st.modal?modal():""}`}
function renderGlobalOnly(){let host=document.getElementById("globalResultsHost");if(host)host.innerHTML=globalResults();let input=document.getElementById("globalInput");if(input&&document.activeElement!==input){input.focus();input.setSelectionRange(input.value.length,input.value.length)}}
function globalResults(){let q=st.global.trim().toLowerCase();if(q.length<2)return "";let contacts=db.contacts.filter(c=>[c.n,c.f,c.m,c.tel,c.e,meta(c)].some(x=>(x||"").toLowerCase().includes(q)));let orgs=db.orgs.filter(o=>[o.n,type(o.t).n].some(x=>x.toLowerCase().includes(q)));let moms=db.mothers.filter(m=>m.n.toLowerCase().includes(q));let kids=db.kids.filter(k=>k.n.toLowerCase().includes(q));function sec(title,items,html,more){if(!items.length)return "";let rest=items.length-5;return `<div class="global-section"><h4>${title} (${items.length})</h4>${items.slice(0,5).map(html).join("")}${rest>0?`<button class="global-more" onclick="${more}">Nog ${rest} resultaten...</button>`:""}</div>`}let out=sec("Contactpersonen",contacts,c=>`<button class="global-item" onclick="nav('contact',${c.id})">${c.n}<br><span class="muted">${meta(c)}</span></button>`,"nav('contacts')")+sec("Organisaties",orgs,o=>`<button class="global-item" onclick="nav('org',${o.id})">${type(o.t).n} | ${o.n}</button>`,"nav('orgs')")+sec("Moeders",moms,m=>`<button class="global-item" onclick="nav('mother',${m.id})">${m.n}</button>`,"nav('mothers')")+sec("Kinderen",kids,k=>`<button class="global-item" onclick="nav('mother',${k.mo})">${k.n}<br><span class="muted">${mother(k.mo).n}</span></button>`,"nav('kids')");if(!out)out=`<div class="muted">Geen resultaten gevonden.</div>`;return `<div class="global-results">${out}</div>`}
function mothersPage(){let q=st.motherQ.toLowerCase();let rows=db.mothers.filter(m=>m.a&&(!q||m.n.toLowerCase().includes(q)));return `<div class="toolbar"><h2>Moeders</h2><button class="btn primary" onclick="openDrawer('mother')">Nieuwe moeder</button></div><div class="filter" style="max-width:560px;margin-bottom:18px"><label>Zoeken</label><input value="${esc(st.motherQ)}" oninput="st.motherQ=this.value;render()" placeholder="Zoek moeder..."></div><div class="grid-cards">${rows.map(m=>`<button class="type-card" onclick="nav('mother',${m.id})"><strong>${m.n}</strong><span>Actief</span></button>`).join("")}</div>`}
function motherPage(id){let m=mother(id),ks=kidsMom(id),cs=consMom(id);return `<button class="back" onclick="nav('mothers')">← Terug naar moeders</button><div class="profile-grid"><div class="card profile"><h2>${m.n}</h2><p>${m.op||""}</p><div class="profile-actions"><button class="btn secondary">Bewerken</button><button class="btn secondary">Inactief maken</button></div></div><div class="card"><div class="side-title">Kinderen</div><div class="simple-list">${ks.map(k=>`<button class="simple-item" onclick="nav('mother',${m.id})">${k.n}</button>`).join("")}<button class="btn primary" style="justify-self:start" onclick="openDrawer('kid',{mother:${id}})">Kind toevoegen</button></div></div></div><div class="panel"><h3>Contactpersonen</h3><div class="list">${cs.map(personRow).join("")}</div><div class="section-actions"><button class="btn primary" onclick="openDrawer('link',{mother:${id}})">Contactpersoon toevoegen</button></div></div>`}
function kidsPage(){let q=st.kidQ.toLowerCase();let groups=db.mothers.filter(m=>m.a).sort((a,b)=>a.n.localeCompare(b.n,'nl')).map(m=>({m,k:kidsMom(m).sort((a,b)=>a.n.localeCompare(b.n,'nl'))})).filter(g=>g.k.length&&(!q||g.k.some(k=>k.n.toLowerCase().includes(q))));return `<div class="toolbar"><h2>Kinderen</h2></div><div class="filter" style="max-width:560px;margin-bottom:18px"><label>Zoeken op kind</label><input value="${esc(st.kidQ)}" oninput="st.kidQ=this.value;render()" placeholder="Naam kind"></div><div class="kid-groups">${groups.map(g=>`<div class="family-card"><button class="mother" onclick="nav('mother',${g.m.id})">${g.m.n}</button>${g.k.map(k=>`<button class="child" onclick="nav('mother',${g.m.id})">${first(k.n)}</button>`).join("")}</div>`).join("")}</div>`}
function contactsPage(){return `<div class="toolbar"><h2>Contactpersonen</h2></div><div class="filters"><div class="filter"><label>Zoeken op naam</label><input id="cName" oninput="renderContactResults()" placeholder="Naam contactpersoon"></div><div class="filter"><label>Type organisatie</label><select id="cType" onchange="updateOrgFilter();renderContactResults()"><option value="all">Alle types</option>${db.types.map(t=>`<option value="${t.id}">${t.n}</option>`).join("")}</select></div><div class="filter"><label>Organisatie</label><select id="cOrg" onchange="renderContactResults()"><option value="all">Alle organisaties</option>${db.orgs.filter(o=>consOrg(o.id).length).map(o=>`<option value="${o.id}">${o.n}</option>`).join("")}</select></div></div><div id="contactInstruction" class="instruction">Voer een naam in of kies een type organisatie of organisatie om bestaande contactpersonen te tonen. Staat de contactpersoon er niet tussen? Kies dan 'Contactpersoon toevoegen'.</div><div id="contactResults" class="list"></div><div class="section-actions"><button class="btn primary" onclick="openDrawer('contact')">Contactpersoon toevoegen</button></div>`}
function updateOrgFilter(){let t=document.getElementById("cType").value,s=document.getElementById("cOrg");s.innerHTML=`<option value="all">Alle organisaties</option>`+db.orgs.filter(o=>(t==="all"||o.t==t)&&consOrg(o.id).length).map(o=>`<option value="${o.id}">${o.n}</option>`).join("")}
function contactFilterResults(){let q=(document.getElementById("cName")?.value||"").toLowerCase(),t=document.getElementById("cType")?.value||"all",o=document.getElementById("cOrg")?.value||"all";if(!q&&t==="all"&&o==="all")return [];return db.contacts.filter(c=>{let oo=org(c.o);return(t==="all"||oo.t==t)&&(o==="all"||c.o==o)&&(!q||c.n.toLowerCase().includes(q))})}
function renderContactResults(){let res=contactFilterResults(),has=(document.getElementById("cName")?.value||"")||document.getElementById("cType")?.value!=="all"||document.getElementById("cOrg")?.value!=="all";document.getElementById("contactInstruction").style.display=has?"none":"block";document.getElementById("contactResults").innerHTML=res.map(c=>`<div class="row"><div class="row-main"><strong>${c.n} | ${c.f||"Geen functie"}</strong><span>${type(org(c.o).t).n} | ${org(c.o).n}</span></div><div class="row-actions"><button class="link-edit">Bewerken</button><button class="link-delete">Verwijderen</button></div></div>`).join("")}
function contactPage(id){let c=contact(id),o=org(c.o),t=type(o.t),ms=db.mothers.filter(m=>c.mo.includes(m.id));return `<button class="back" onclick="nav('contacts')">← Terug</button><div class="hero"><h2>${c.n}</h2><p>${c.f||""}</p></div><div class="detail-grid"><div class="panel">${info("Type organisatie",t.n)}${info("Organisatie",o.n)}${info("Mobiel",c.m||"—")}${info("Telefoon",c.tel||"—")}${info("E-mail",c.e||"—")}${info("Opmerkingen",c.op||"—")}<div class="form-actions"><button class="btn secondary">Bewerken</button><button class="btn danger">Verwijderen</button></div></div><div class="panel"><h3>Moeders</h3><div class="chips">${ms.map(m=>`<button onclick="nav('mother',${m.id})">${m.n}</button>`).join("")}</div></div></div>`}
function orgsPage(){return `<div class="toolbar"><h2>Organisaties</h2></div><div class="grid-cards">${db.types.map(t=>`<button class="type-card" onclick="nav('type',${t.id})"><strong>${t.n}</strong><span>${db.orgs.filter(o=>o.t==t.id).length} organisaties</span></button>`).join("")}</div><div class="section-actions"><button class="btn primary" onclick="openModal('type')">Nieuw type organisatie</button></div>`}
function typePage(id){let t=type(id),rows=db.orgs.filter(o=>o.t==id);return `<button class="back" onclick="nav('orgs')">← Terug naar organisaties</button><div class="toolbar"><h2>${t.n}</h2></div><div class="grid-cards">${rows.map(o=>`<button class="type-card" onclick="nav('org',${o.id})"><strong>${o.n}</strong><span>${consOrg(o.id).length} contactpersonen</span></button>`).join("")}</div><div class="section-actions"><button class="btn primary" onclick="openModal('org',{type:${id}})">Nieuwe organisatie</button></div>`}
function orgPage(id){let o=org(id),t=type(o.t),cs=consOrg(id);return `<button class="back" onclick="nav('type',${o.t})">← Terug naar ${t.n}</button><div class="hero"><h2>${t.n}</h2><p><strong>${o.n}</strong></p></div><div class="panel"><h3>Contactpersonen</h3><div class="list">${cs.map(personRow).join("")}</div><div class="section-actions"><button class="btn primary" onclick="openDrawer('contact',{org:${id}})">Contactpersoon toevoegen</button></div></div>`}
function personRow(c){return `<div class="row"><div class="row-main"><strong>${c.n} | ${c.f||"Geen functie"}</strong></div><div class="row-actions"><button class="link-edit">Bewerken</button><button class="link-delete">Verwijderen</button></div></div>`}
function drawer(){let d=st.drawer;if(d.kind==="mother")return drawMother();if(d.kind==="kid")return drawKid();if(d.kind==="contact")return drawContact();if(d.kind==="link")return drawLink()}
function drawMother(){return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuwe moeder</h2><div class="field"><label>Naam</label><input id="mn" autofocus></div><div class="field"><label>Opmerkingen</label><textarea id="mop"></textarea></div><div class="form-actions"><button class="btn secondary" onclick="closeDrawer()">Annuleren</button><button class="btn primary" onclick="saveMother()">Opslaan</button></div></aside></div>`}
function drawKid(){let mid=st.drawer.ctx.mother||db.mothers.find(m=>m.a).id;return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuw kind</h2><div class="field"><label>Naam</label><input id="kn" autofocus></div><div class="field"><label>Moeder</label><select id="km">${db.mothers.filter(m=>m.a).map(m=>`<option value="${m.id}" ${m.id==mid?"selected":""}>${m.n}</option>`).join("")}</select></div><div class="form-actions"><button class="btn secondary" onclick="closeDrawer()">Annuleren</button><button class="btn primary" onclick="saveKid()">Opslaan</button></div></aside></div>`}
function drawContact(){let oid=st.drawer.ctx.org||db.orgs[0].id,o=org(oid),tid=o.t;return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuwe contactpersoon</h2>${st.drawer.ctx.mother?`<input id="cmo" type="hidden" value="${st.drawer.ctx.mother}">`:""}<div class="field"><label>Type organisatie</label><select id="ct" onchange="orgAuto()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Organisatie</label><div class="form-row"><input id="oterm" value="${esc(o.n)}" oninput="orgAuto()" placeholder="Typ organisatie..."><button class="btn secondary" onclick="openModal('org',{type:+document.getElementById('ct').value})">Nieuw</button></div><input id="selorg" type="hidden" value="${oid}"><div id="omatch"></div></div><div class="field"><label>Naam</label><input id="cn"></div><div class="field"><label>Functie</label><input id="cf"></div><div class="field"><label>Mobiel</label><input id="cmob"></div><div class="field"><label>Telefoon</label><input id="ctel"></div><div class="field"><label>E-mail</label><input id="ce"></div><div class="field"><label>Opmerkingen</label><textarea id="cop"></textarea></div><div id="warn"></div><div class="form-actions"><button class="btn secondary" onclick="closeDrawer()">Annuleren</button><button class="btn primary" onclick="saveContact()">Opslaan</button></div></aside></div>`}
function drawLink(){let mid=st.drawer.ctx.mother,tid=st.drawer.ctx.type||db.types[0].id,orgs=db.orgs.filter(o=>o.t==tid),oid=st.drawer.ctx.org||orgs[0].id,cs=db.contacts.filter(c=>c.o==oid&&!c.mo.includes(mid));return `<div class="drawer-bg"><aside class="drawer"><h2>Contactpersoon toevoegen</h2><div class="field"><label>Type organisatie</label><select onchange="st.drawer.ctx.type=+this.value;st.drawer.ctx.org=null;render()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Organisatie</label><div class="form-row"><select onchange="st.drawer.ctx.org=+this.value;render()">${orgs.map(o=>`<option value="${o.id}" ${o.id==oid?"selected":""}>${o.n}</option>`).join("")}</select><button class="btn secondary" onclick="openModal('org',{type:${tid}})">Nieuw</button></div></div><h3>Bekende contactpersonen</h3><div class="list">${cs.map(c=>`<button class="row" onclick="linkCon(${c.id},${mid})"><div class="row-main"><strong>${c.n} | ${c.f||"Geen functie"}</strong></div><div>›</div></button>`).join("")}</div><div class="section-actions"><button class="btn primary" onclick="openDrawer('contact',{mother:${mid},org:${oid}})">Nieuwe contactpersoon</button></div><div class="form-actions"><button class="btn secondary" onclick="closeDrawer()">Sluiten</button></div></aside></div>`}
function modal(){if(st.modal.kind==="type")return `<div class="modal-bg"><div class="modal"><h2>Nieuw type organisatie</h2><div class="field"><label>Naam</label><input id="tn" autofocus></div><div class="form-actions"><button class="btn secondary" onclick="closeModal()">Annuleren</button><button class="btn primary" onclick="saveType()">Opslaan</button></div></div></div>`;let tid=st.modal.ctx.type||1;return `<div class="modal-bg"><div class="modal"><h2>Nieuwe organisatie</h2><div class="field"><label>Type organisatie</label><select id="nt">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Naam organisatie</label><input id="on" oninput="orgSuggest()" autofocus><div id="orgSuggest"></div></div><div class="form-actions"><button class="btn secondary" onclick="closeModal()">Annuleren</button><button class="btn primary" onclick="saveOrg()">Opslaan</button></div></div></div>`}
function orgSuggest(){let n=v("on").toLowerCase(),t=+v("nt"),m=db.orgs.filter(o=>o.t==t&&n&&o.n.toLowerCase().includes(n));document.getElementById("orgSuggest").innerHTML=m.length?`<div class="autocomplete">${m.map(o=>`<button onclick="nav('org',${o.id})">${o.n}</button>`).join("")}</div>`:""}
function orgAuto(){let tid=+v("ct"),term=v("oterm").toLowerCase(),m=db.orgs.filter(o=>o.t==tid&&(!term||o.n.toLowerCase().includes(term)));document.getElementById("omatch").innerHTML=`<div class="autocomplete">${m.map(o=>`<button onclick="selectOrg(${o.id})">${o.n}</button>`).join("")}</div>`}
function selectOrg(id){document.getElementById("selorg").value=id;document.getElementById("oterm").value=org(id).n;document.getElementById("omatch").innerHTML=""}
function saveMother(){let n=v("mn"),op=v("mop");if(!n)return alert("Vul een naam in.");let id=nid(db.mothers);db.mothers.push({id,n,op,a:1,k:[]});nav("mother",id)}
function saveKid(){let n=v("kn"),mo=+v("km");if(!n)return alert("Vul een naam in.");let id=nid(db.kids);db.kids.push({id,n,mo});mother(mo).k.push(id);closeDrawer()}
function saveType(){let n=v("tn");if(!n)return alert("Vul een naam in.");if(db.types.some(t=>t.n.toLowerCase()==n.toLowerCase()))return alert("Dit type organisatie bestaat al.");db.types.push({id:nid(db.types),n});closeModal()}
function saveOrg(){let n=v("on"),t=+v("nt");if(!n)return alert("Vul een naam organisatie in.");if(db.orgs.some(o=>o.t==t&&o.n.toLowerCase()==n.toLowerCase()))return alert("Deze organisatie bestaat al binnen dit type organisatie.");db.orgs.push({id:nid(db.orgs),t,n});closeModal()}
function saveContact(force=false){let o=+v("selorg"),n=v("cn"),m=v("cmob"),e=v("ce");if(!o)return alert("Kies een organisatie.");if(!n)return alert("Vul een naam in.");if(!force){let dup=db.contacts.find(c=>(c.o==o&&c.n.toLowerCase()==n.toLowerCase())||(m&&c.m==m)||(e&&c.e.toLowerCase()==e.toLowerCase()));if(dup){document.getElementById("warn").innerHTML=`<div class="warning"><strong>Mogelijke dubbele contactpersoon</strong>${dup.n}<br>${meta(dup)}<div class="form-actions"><button class="btn secondary" onclick="nav('contact',${dup.id})">Bestaande openen</button><button class="btn primary" onclick="saveContact(true)">Toch opslaan</button></div></div>`;return}}let id=nid(db.contacts),mo=+(document.getElementById("cmo")?.value||0);db.contacts.push({id,o,n,f:v("cf"),m,tel:v("ctel"),e,op:v("cop"),mo:mo?[mo]:[]});closeDrawer()}
function linkCon(cid,mid){let c=contact(cid);if(!c.mo.includes(mid))c.mo.push(mid);closeDrawer()}
function info(l,x){return `<div class="info-row"><label>${l}</label><strong>${x}</strong></div>`}
function first(n){return n.split(" ")[0]}
function v(id){return document.getElementById(id)?.value.trim()||""}
function esc(s){return String(s||"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function render(){let c="";if(st.page==="mothers")c=mothersPage();else if(st.page==="mother")c=motherPage(st.id);else if(st.page==="kids")c=kidsPage();else if(st.page==="contacts")c=contactsPage();else if(st.page==="contact")c=contactPage(st.id);else if(st.page==="orgs")c=orgsPage();else if(st.page==="type")c=typePage(st.id);else if(st.page==="org")c=orgPage(st.id);app.innerHTML=shell(c)}
render();
