
let db={
  types:[{id:1,n:"Gemeente"},{id:2,n:"Jeugdbescherming"},{id:3,n:"Veilig Thuis"},{id:4,n:"GGD"},{id:5,n:"Politie"}],
  orgs:[{id:1,t:1,n:"Almelo"},{id:2,t:1,n:"Hengelo"},{id:3,t:1,n:"Tubbergen"},{id:4,t:2,n:"JBOV"},{id:5,t:2,n:"Leger des Heils"},{id:6,t:3,n:"Veilig Thuis Twente"}],
  contacts:[
    {id:1,o:1,n:"Jan Jansen",f:"Jeugdconsulent",m:"06-12345678",tel:"0546-123456",e:"jan.jansen@almelo.nl",op:"Werkt ma-do",mo:[1]},
    {id:2,o:1,n:"Harry Nak",f:"Contractmanager",m:"0612457896",tel:"",e:"",op:"di-do",mo:[1]},
    {id:3,o:4,n:"Nico de Groot",f:"Jeugdbeschermer",m:"06-12365478",tel:"",e:"",op:"Alleen mailen",mo:[1]},
    {id:4,o:6,n:"Petra de Vries",f:"Adviseur",m:"06-87654321",tel:"",e:"petra@example.nl",op:"",mo:[2]}
  ],
  mothers:[
    {id:1,n:"Maria Jansen",op:"Voorkeur telefonisch contact.",a:1,k:[1,2]},
    {id:2,n:"Anne de Vries",op:"Eerst via contactpersoon afstemmen.",a:1,k:[3]},
    {id:3,n:"Karin Bakker",op:"",a:1,k:[5,6,7]},
    {id:4,n:"Moeder Oud",op:"Niet meer actief.",a:0,k:[4]}
  ],
  kids:[
    {id:1,n:"Lisa Jansen",mo:1},{id:2,n:"Milan Jansen",mo:1},{id:3,n:"Saar de Vries",mo:2},{id:4,n:"Oud Kind",mo:4},{id:5,n:"Emma Bakker",mo:3},{id:6,n:"Julia Bakker",mo:3},{id:7,n:"Noah Bakker",mo:3}
  ]
};
let st={p:"mothers",id:null,q:"",inline:"",kidq:"",d:null,modal:null,ct:"all",co:"all"};
const app=document.getElementById("app");
const by=(a,id)=>a.find(x=>x.id==id), type=id=>by(db.types,id), org=id=>by(db.orgs,id), con=id=>by(db.contacts,id), mom=id=>by(db.mothers,id), nid=a=>Math.max(0,...a.map(x=>x.id))+1;
function consOrg(id){return db.contacts.filter(c=>c.o==id)}
function consMom(id){return db.contacts.filter(c=>c.mo.includes(+id))}
function kidsMom(id){return db.kids.filter(k=>k.mo==id)}
function meta(c){let o=org(c.o),t=type(o.t);return `${t.n} | ${o.n} | ${c.f||""}`}
function go(p,id=null){st={...st,p,id,q:"",inline:"",d:null,modal:null}; if(p==="contacts"){st.ct="all";st.co="all"} render()}
function sq(v){st.q=v;render()}
function si(v){st.inline=v;render()}
function od(k,ctx={}){st.d={k,ctx};st.modal=null;render()}
function cd(){st.d=null;st.modal=null;render()}
function om(k,ctx={}){st.modal={k,ctx};render()}
function cm(){st.modal=null;render()}
function shell(c){return `<div class="app"><aside class="sidebar"><div class="brand"><img src="./logo.png" onerror="this.style.display='none'"><div><div class="brand-title">Contacten</div><div class="brand-org">Het Twentse Geluk</div></div></div><div class="global-search"><input value="${esc(st.q)}" oninput="sq(this.value)" placeholder="Zoek overal..."></div><nav class="nav"><button class="${st.p==="mothers"?"active":""}" onclick="go('mothers')">Moeders</button><button class="${st.p==="kids"?"active":""}" onclick="go('kids')">Kinderen</button><button class="${["contacts","contact"].includes(st.p)?"active":""}" onclick="go('contacts')">Contactpersonen</button><button class="${["orgs","type","org"].includes(st.p)?"active":""}" onclick="go('orgs')">Organisaties</button></nav></aside><main class="main">${c}</main></div>${globalResults()}${st.d?drawer():""}${st.modal?modal():""}`}
function home(){return `<div class="hero"><h2>Contacten</h2></div><div class="home-actions"><button onclick="od('mother')">Nieuwe moeder</button><button onclick="od('kid')">Nieuw kind</button><button onclick="od('contact')">Nieuw contactpersoon</button><button onclick="om('org')">Nieuwe organisatie</button></div>`}
function orgs(){let ts=db.types;return `<div class="toolbar"><h2>Organisaties</h2><div class="actions"><button class="btn btn-primary" onclick="om('org')">Nieuwe organisatie</button><button class="btn btn-primary" onclick="om('type')">Nieuw type organisatie</button></div></div><div class="type-grid">${ts.map(t=>`<button class="type-card" onclick="go('type',${t.id})"><strong>${t.n}</strong><span>${db.orgs.filter(o=>o.t==t.id).length} organisaties</span></button>`).join("")}</div>`}
function typePage(id){let t=type(id), rows=db.orgs.filter(o=>o.t==id);return `<button class="back" onclick="go('orgs')">← Terug naar organisaties</button><div class="toolbar"><h2>${t.n}</h2><button class="btn btn-primary" onclick="od('contact',{type:${id}})">Nieuwe contactpersoon</button></div><div class="cards">${rows.map(o=>`<button class="row-card" onclick="go('org',${o.id})"><div><strong>${o.n}</strong></div><div><span>${consOrg(o.id).length} contactpersonen</span></div><div class="chev">›</div></button>`).join("")}</div>`}
function orgPage(id){let o=org(id),t=type(o.t),cs=consOrg(id);return `<button class="back" onclick="go('type',${o.t})">← Terug naar ${t.n}</button><div class="hero"><h2>${t.n}</h2><p><strong>${o.n}</strong></p></div><div class="panel"><h3>Contactpersonen</h3><div class="cards">${cs.map(c=>personActionRow(c)).join("")}</div><div class="section-actions"><button class="btn btn-primary" onclick="od('contact',{org:${id}})">Contactpersoon toevoegen</button></div></div>`}
function personActionRow(c){return `<div class="row-card"><div><strong>${c.n} | ${c.f||"Geen functie"}</strong></div><div></div><div class="row-actions"><button class="link-edit">Bewerken</button><button class="link-delete">Verwijderen</button></div></div>`}
function contactRow(c){return `<button class="row-card" onclick="go('contact',${c.id})"><div><strong>${c.n}</strong></div><div><span>${meta(c)}</span></div><div class="chev">›</div></button>`}
function contactPage(id){let c=con(id),o=org(c.o),t=type(o.t),ms=db.mothers.filter(m=>c.mo.includes(m.id));return `<button class="back" onclick="go('contacts')">← Terug</button><div class="hero"><h2>${c.n}</h2><p>${c.f||""}</p></div><div class="detail-grid"><div class="panel">${info("Type organisatie",t.n)}${info("Organisatie",o.n)}${info("Mobiel",c.m||"—")}${info("Telefoon",c.tel||"—")}${info("E-mail",c.e||"—")}${info("Opmerkingen",c.op||"—")}<div class="form-actions"><button class="btn btn-secondary">Bewerken</button><button class="btn btn-danger">Verwijderen</button></div></div><div class="panel"><h3>Moeders</h3><div class="chips">${ms.map(m=>`<button onclick="go('mother',${m.id})">${m.n}</button>`).join("")}</div></div></div>`}
function mothers(){let rows=db.mothers.filter(m=>m.a&&(!st.inline||m.n.toLowerCase().includes(st.inline.toLowerCase())));return `<div class="toolbar"><h2>Moeders</h2><button class="btn btn-primary" onclick="od('mother')">Nieuwe moeder</button></div><div class="filter" style="max-width:560px;margin-bottom:18px"><label>Zoeken</label><input value="${esc(st.inline)}" oninput="si(this.value)" placeholder="Zoek moeder..."></div><div class="cards">${rows.map(m=>`<button class="row-card" onclick="go('mother',${m.id})"><div><strong>${m.n}</strong></div><div><span>Actief</span></div><div class="chev">›</div></button>`).join("")}</div>`}
function motherPage(id){let m=mom(id),ks=kidsMom(id),cs=consMom(id);return `<button class="back" onclick="go('mothers')">← Terug naar moeders</button><div class="profile-grid"><div class="profile-card"><h2>${m.n}</h2><p>${m.op||""}</p><div class="profile-actions"><button class="btn btn-secondary">Bewerken</button><button class="btn btn-secondary">Inactief maken</button></div></div><div class="profile-card"><div class="side-title">Kinderen</div><div class="simple-list">${ks.map(k=>`<button class="simple-item" onclick="go('mother',${m.id})">${k.n}</button>`).join("")}<button class="btn btn-primary compact-add" onclick="od('kid',{mother:${id}})">Kind toevoegen</button></div></div></div><div class="panel"><h3>Contactpersonen</h3><div class="cards">${cs.map(c=>personActionRow(c)).join("")}</div><div class="section-actions"><button class="btn btn-primary" onclick="od('link',{mother:${id}})">Contactpersoon toevoegen</button></div></div>`}
function kids(){let q=(st.kidq||"").toLowerCase();let groups=db.mothers.filter(m=>m.a).sort((a,b)=>a.n.localeCompare(b.n,'nl')).map(m=>({m,k:kidsMom(m).sort((a,b)=>a.n.localeCompare(b.n,'nl'))})).filter(g=>g.k.length&&(!q||g.k.some(k=>k.n.toLowerCase().includes(q))));return `<div class="toolbar"><h2>Kinderen</h2></div><div class="filter kid-search"><label>Zoeken op kind</label><input value="${esc(st.kidq||"")}" oninput="st.kidq=this.value;render()" placeholder="Naam kind"></div><div class="kid-groups">${groups.map(g=>`<div class="kid-group"><button class="kid-mother" onclick="go('mother',${g.m.id})">${g.m.n}</button>${g.k.map(k=>`<button class="kid-child" onclick="go('mother',${g.m.id})">${first(k.n)}</button>`).join("")}</div>`).join("")}</div>`}
function first(n){return n.split(" ")[0]}
function kidPage(id){let k=by(db.kids,id);return motherPage(k.mo)}
function drawer(){let d=st.d;if(d.k==="mother")return drawMother();if(d.k==="kid")return drawKid();if(d.k==="contact")return drawContact();if(d.k==="link")return drawLink()}
function drawMother(){return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuwe moeder</h2><div class="field"><label>Naam</label><input id="mn" autofocus></div><div class="field"><label>Opmerkingen</label><textarea id="mop"></textarea></div><div class="form-actions"><button class="btn btn-secondary" onclick="cd()">Annuleren</button><button class="btn btn-primary" onclick="saveMother()">Opslaan</button></div></aside></div>`}
function drawKid(){let mid=st.d.ctx.mother||db.mothers.find(m=>m.a).id;return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuw kind</h2><div class="field"><label>Naam</label><input id="kn" autofocus></div><div class="field"><label>Moeder</label><select id="km">${db.mothers.filter(m=>m.a).map(m=>`<option value="${m.id}" ${m.id==mid?"selected":""}>${m.n}</option>`).join("")}</select></div><div class="form-actions"><button class="btn btn-secondary" onclick="cd()">Annuleren</button><button class="btn btn-primary" onclick="saveKid()">Opslaan</button></div></aside></div>`}
function drawContact(){let oid=st.d.ctx.org||db.orgs[0].id,o=org(oid),tid=st.d.ctx.type||o.t;return `<div class="drawer-bg"><aside class="drawer"><h2>Nieuwe contactpersoon</h2>${st.d.ctx.mother?`<input id="cmo" type="hidden" value="${st.d.ctx.mother}">`:""}${typePick(tid)}${orgAuto(oid)}<div class="field"><label>Naam</label><input id="cn"></div><div class="field"><label>Functie</label><input id="cf"></div><div class="field"><label>Mobiel</label><input id="cmob"></div><div class="field"><label>Telefoon</label><input id="ctel"></div><div class="field"><label>E-mail</label><input id="ce"></div><div class="field"><label>Opmerkingen</label><textarea id="cop"></textarea></div><div id="warn"></div><div class="form-actions"><button class="btn btn-secondary" onclick="cd()">Annuleren</button><button class="btn btn-primary" onclick="saveContact()">Opslaan</button></div></aside></div>`}
function typePick(tid){return `<div class="field"><label>Type organisatie</label><select id="ct" onchange="updateOrgAuto()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div>`}
function orgAuto(oid){let o=org(oid);return `<div class="field"><label>Organisatie</label><div class="form-row"><input id="oterm" value="${esc(o.n)}" oninput="updateOrgAuto()" placeholder="Typ organisatie..."><button class="btn btn-secondary" onclick="om('org')">Nieuw</button></div><input id="selorg" type="hidden" value="${oid}"><div id="omatch"></div></div>`}
function drawLink(){let mid=st.d.ctx.mother,tid=st.d.ctx.type||db.types[0].id,orgs=db.orgs.filter(o=>o.t==tid),oid=st.d.ctx.org||orgs[0].id,cs=db.contacts.filter(c=>c.o==oid&&!c.mo.includes(mid));return `<div class="drawer-bg"><aside class="drawer"><h2>Contactpersoon toevoegen</h2><div class="field"><label>Type organisatie</label><select onchange="st.d.ctx.type=+this.value;st.d.ctx.org=null;render()">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Organisatie</label><div class="form-row"><select onchange="st.d.ctx.org=+this.value;render()">${orgs.map(o=>`<option value="${o.id}" ${o.id==oid?"selected":""}>${o.n}</option>`).join("")}</select><button class="btn btn-secondary" onclick="om('org')">Nieuw</button></div></div><h3>Bekende contactpersonen</h3><div class="cards">${cs.map(c=>`<button class="row-card" onclick="linkCon(${c.id},${mid})"><div><strong>${c.n}</strong></div><div><span>${meta(c)}</span></div><div class="chev">›</div></button>`).join("")}</div><div class="section-actions"><button class="btn btn-primary" onclick="od('contact',{mother:${mid},org:${oid}})">Nieuwe contactpersoon</button></div><div class="form-actions"><button class="btn btn-secondary" onclick="cd()">Sluiten</button></div></aside></div>`}
function modal(){if(st.modal.k==="type")return `<div class="modal-bg"><div class="modal"><h2>Nieuw type organisatie</h2><div class="field"><label>Naam</label><input id="tn" autofocus></div><div class="form-actions"><button class="btn btn-secondary" onclick="cm()">Annuleren</button><button class="btn btn-primary" onclick="saveType()">Opslaan</button></div></div></div>`;let tid=+(document.getElementById("ct")?.value||st.d?.ctx?.type||1);return `<div class="modal-bg"><div class="modal"><h2>Nieuwe organisatie</h2><div class="field"><label>Type organisatie</label><select id="nt">${db.types.map(t=>`<option value="${t.id}" ${t.id==tid?"selected":""}>${t.n}</option>`).join("")}</select></div><div class="field"><label>Naam organisatie</label><input id="on" oninput="orgSuggest()" autofocus><div id="orgSuggest"></div></div><div class="form-actions"><button class="btn btn-secondary" onclick="cm()">Annuleren</button><button class="btn btn-primary" onclick="saveOrg()">Opslaan</button></div></div></div>`}
function orgSuggest(){let n=v("on").toLowerCase(),t=+v("nt"),m=db.orgs.filter(o=>o.t==t&&n&&o.n.toLowerCase().includes(n));let el=document.getElementById("orgSuggest");if(el)el.innerHTML=m.length?`<div class="autocomplete">${m.map(o=>`<button onclick="go('org',${o.id})">${o.n}</button>`).join("")}</div>`:""}
function saveMother(){let n=v("mn"),op=v("mop");if(!n)return alert("Vul een naam in.");let id=nid(db.mothers);db.mothers.push({id,n,op,a:1,k:[]});go("mother",id)}
function saveKid(){let n=v("kn"),mo=+v("km");if(!n)return alert("Vul een naam in.");let id=nid(db.kids);db.kids.push({id,n,mo});mom(mo).k.push(id);cd()}
function saveType(){let n=v("tn");if(!n)return alert("Vul een naam in.");if(db.types.some(t=>t.n.toLowerCase()==n.toLowerCase()))return alert("Dit type organisatie bestaat al.");db.types.push({id:nid(db.types),n});cm()}
function saveOrg(){let n=v("on"),t=+v("nt");if(!n)return alert("Vul een naam organisatie in.");if(db.orgs.some(o=>o.t==t&&o.n.toLowerCase()==n.toLowerCase()))return alert("Deze organisatie bestaat al binnen dit type organisatie.");let id=nid(db.orgs);db.orgs.push({id,t,n});cm()}
function saveContact(force=false){let o=+v("selorg"),n=v("cn"),m=v("cmob"),e=v("ce");if(!o)return alert("Kies een organisatie.");if(!n)return alert("Vul een naam in.");if(!force){let dup=db.contacts.find(c=>(c.o==o&&c.n.toLowerCase()==n.toLowerCase())||(m&&c.m==m)||(e&&c.e.toLowerCase()==e.toLowerCase()));if(dup){document.getElementById("warn").innerHTML=`<div class="warning"><strong>Mogelijke dubbele contactpersoon</strong>${dup.n}<br>${meta(dup)}<div class="form-actions"><button class="btn btn-secondary" onclick="go('contact',${dup.id})">Bestaande openen</button><button class="btn btn-primary" onclick="saveContact(true)">Toch opslaan</button></div></div>`;return}}let id=nid(db.contacts),mo=+(document.getElementById("cmo")?.value||0);db.contacts.push({id,o,n,f:v("cf"),m,tel:v("ctel"),e,op:v("cop"),mo:mo?[mo]:[]});cd()}
function linkCon(cid,mid){let c=con(cid);if(!c.mo.includes(mid))c.mo.push(mid);cd()}
function updateOrgAuto(){let tid=+v("ct"),term=v("oterm").toLowerCase(),matches=db.orgs.filter(o=>o.t==tid&&(!term||o.n.toLowerCase().includes(term)));document.getElementById("omatch").innerHTML=`<div class="autocomplete">${matches.map(o=>`<button onclick="selectOrg(${o.id})">${o.n}</button>`).join("")}</div>`}
function selectOrg(id){document.getElementById("selorg").value=id;document.getElementById("oterm").value=org(id).n;document.getElementById("omatch").innerHTML=""}
function searchPage(){let q=st.q.toLowerCase();return `<div class="hero"><h2>Resultaten voor “${esc(st.q)}”</h2></div>${group("Contactpersonen",db.contacts.filter(c=>[c.n,meta(c),c.m,c.e].some(x=>(x||"").toLowerCase().includes(q))).map(contactRow))}${group("Moeders",db.mothers.filter(m=>m.n.toLowerCase().includes(q)).map(m=>`<button class="simple-item" onclick="go('mother',${m.id})">${m.n}</button>`))}`}
function group(t,rows){return `<section class="panel"><h3>${t}</h3><div class="cards">${rows.length?rows.join(""):`<p class="muted">Geen resultaten.</p>`}</div></section>`}
function info(l,x){return `<div class="info-row"><label>${l}</label><strong>${x}</strong></div>`}
function v(id){return document.getElementById(id)?.value.trim()||""}
function esc(s){return String(s||"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}

function globalResults(){
  if(!st.q || st.q.trim().length<2) return "";
  let q=st.q.toLowerCase();
  let contacts=db.contacts.filter(c=>[c.n,c.f,c.m,c.tel,c.e,meta(c)].some(x=>(x||"").toLowerCase().includes(q)));
  let orgs=db.orgs.filter(o=>[o.n,type(o.t).n].some(x=>x.toLowerCase().includes(q)));
  let moms=db.mothers.filter(m=>m.n.toLowerCase().includes(q));
  let kids=db.kids.filter(k=>k.n.toLowerCase().includes(q));
  function section(title,items,html,moreAction){
    if(!items.length) return "";
    let more=items.length-5;
    return `<div class="global-section"><h4>${title} (${items.length})</h4>${items.slice(0,5).map(html).join("")}${more>0?`<button class="global-more" onclick="${moreAction}">Nog ${more} resultaten...</button>`:""}</div>`;
  }
  let out =
    section("Contactpersonen",contacts,c=>`<button class="global-item" onclick="go('contact',${c.id})">${c.n}<br><span class="muted">${meta(c)}</span></button>`,"go('contacts')")+
    section("Organisaties",orgs,o=>`<button class="global-item" onclick="go('org',${o.id})">${type(o.t).n} | ${o.n}</button>`,"go('orgs')")+
    section("Moeders",moms,m=>`<button class="global-item" onclick="go('mother',${m.id})">${m.n}</button>`,"go('mothers')")+
    section("Kinderen",kids,k=>`<button class="global-item" onclick="go('mother',${k.mo})">${k.n}<br><span class="muted">${mom(k.mo).n}</span></button>`,"go('kids')");
  if(!out) out=`<div class="muted">Geen resultaten gevonden.</div>`;
  return `<div class="global-results">${out}</div>`;
}

function render(){let c="";if(st.q)c=searchPage();else if(st.p==="home")c=home();else if(st.p==="orgs")c=orgs();else if(st.p==="type")c=typePage(st.id);else if(st.p==="org")c=orgPage(st.id);else if(st.p==="contacts")c=contacts();else if(st.p==="contact")c=contactPage(st.id);else if(st.p==="mothers")c=mothers();else if(st.p==="mother")c=motherPage(st.id);else if(st.p==="kids")c=kids();else if(st.p==="kid")c=kidPage(st.id);app.innerHTML=shell(c)}
render();
